#!/bin/sh
#Hook script to validate all JSON files that were pushed

for file in $(git diff-index --name-only --diff-filter=ACM --cached HEAD -- \
    | grep -P '\.(json)$'); do
    python -mjson.tool $file 2> /dev/null
    if [ $? -ne 0 ] ; then
        echo "JSON object is not valid. Your changes were not pushed."
        echo "in $git_dir/$file:"
        python -mjson.tool $file
        exit 1
    fi
done
